layout_spectrum: 1
color:
  saturation: 0.7406015
  brandStrength: 0.06488013
  lightness: 1
  rhythmicContrast: 0.3210582
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 1
name: Lovely Indeed Events
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/87b380ba-c65e-417e-820c-813d4fe9b70a.png
